name: Bitcoinlib Tests Ubuntu - mariadb
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
          python-version: '3.10'
          architecture: 'x64'
    - uses: getong/mariadb-action@v1.11
      with:
        mysql database: bitcoinlib_test
        mysql user: root
        mysql password: root
    - name: Install dependencies
      run: |
        python -m pip install .[dev]
    - run: |
        python -m pip install mariadb
    - name: Test with coverage
      env:
        BCL_CONFIG_FILE: ${{ github.workspace }}/tests/config.ini.unittest
        UNITTEST_DATABASE: mysql
      run: coverage run --source=bitcoinlib -m unittest -v
